language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install tox
script:
- tox
env:
- TOXENV=
- TOXENV=coverage
notifications:
  slack:
    secure: QVhlHVTMjtt5xwpF2936+gdB3iriawm4DyKd3kWMD8IPvXER+z7xSti41FQVIP99bkkfmHxvmBu/e7Sofvn7W/aK4LnZ31p1AkvnR7v0VGH6lZ8KbJFk5CJV5cR8pDRigPOB3D4i09MhiBtTdRBc/rNFiBWmJ0mwze6K8y5Bm5Mg/Ai26Fn/bMs9nxxoTDzcjgKMHelKwUatMaTCT2E1mKJftJ7KNXK5b0AoAd0T15nQ/z/0RaiRc6NKypr14kuNFJARVRR48FfSNsGKhLNy1dJKEAdPiOrD4I9VC6tbnOwhG6pc9zLD6sUlmIt6bdmJQTutN8WG06PSD5SiX78KZqsxpsfvkXsDulw+lwlI5Fb97G9MLNPVxTou2jyymm0p/DEJa9S+lDrzuuMEgipYRJxl7KtOf9kib+A4nYlQUgqXm9TSJsTpWo00+oF+EuKmKz0mqwbGXDWqZ0L0InXZ4hY0j6EYLpt/47BORBevNJjn1UDzWfDOAa0h55YLKuKiRcxuLofGeVoBES0gYdM2Q9dMWV/9qQPI5LiAFjvl+yU4rY1iue67KbPUxqaInUWaMofAgY0su2EYsevndQaWUrngkuI8HnxGNeTVMFJAzGDUm28FfbWUfHs6a7Muf8DkHRNtXbJDp6+yAwuFMYPxOTFgzhctNgRKx5JRjbvYmTU=
  email:
    recipients:
    - fab@mozaik.life
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: millerf
  password:
    secure: fge3nWckd/APmSonDR8cyODVAmMiDWrA46fG1C9RzYyupDhtLOImtb2UdWaYfJECCO+Sc5LqM+mw9lfXFiLn0wput4zSzQgH7tu9IC4HeAHuD7QCZm0eZZGn6TKP0NyI7M4Dy/hbAsqMNyTvQQv1V9mhce4sLy7lyfZytY/jQx1a6TkdzY8tjWhovk5FBPGTQfqusHLv9QiWtwxA4nZvJVMu68Tf0BIYCvUXUziCTBk0A/gvICfyjO7lMK45E+MwNKP+A4zUm1y/ya1Ppq6mHMOXTXYBqE1D2WQyVDkaoGjuDCqblz1/0yvZN9Wql8X26XU88CApZVG/SEqc6Mf6eW3YxyRzaUWlQNlZlCnfYE+Czil2/ndRd9IhToWdvpvgARrzRS7tO0vuAgAt05Eg8q8vwByJt329TeS8hMIqgvHYaMqRfdo21a0ZESJHXagSvDNVE9UnM1wgfO29ENKy0aWorYB8dUxUkVGO1Dy8dq7F3Lss+Vy9NPwfi9mZi5W2TUJe8rh+C91S9OcRkrqoiAOC1rv9uxeqGND6vWQ6JL4fguqpDDvllmB1wkTg46vV++42J0fkTUBfd9YrSxdg/eSN+voCgMmL6cTK+mdbvHVTZzgbk3gAZ7Tvds80mh2OjkUctJl56RMowhDmHQHoipFnQ9phLwvNTxf/x5OByV0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: millerf/django-channels-jsonrpc
